---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

# Download and Unzip the csv file from the provided url link
```{r}
url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
temp <- tempfile()
file <- download.file(url, temp)
con <- unzip(temp, file, files = NULL) 
data <- read.table("activity.csv", sep=",", header=TRUE, na.strings="NA") 
datedownload <- date()
```
```{r, echo=TRUE}
head(data)
```
# What is the mean total number of steps taken per day?
```{r}
StepsTotal <- aggregate(steps ~ date, data = data, sum, na.rm = TRUE)
```
```{r, echo =TRUE}
hist(StepsTotal$steps, main = "Total steps by day", xlab = "day", col = "purple")
```
```{r, echo=TRUE}
mean(StepsTotal$steps) 
median(StepsTotal$steps) 
```

# What is the average daily activity pattern?
```{r}
time_series <- tapply(data$steps, data$interval, mean, na.rm = TRUE)
```
```{r, echo =TRUE}
plot(row.names(time_series), time_series, type = "l", xlab = "5-min interval", ylab = "Average across all Days", main = "Average number of steps taken", col = "purple")
```
# Imputing missing values
the amount of rows with NAs is 2304
```{r}
count_NA <- sum(is.na(data)) 

StepsAverage <- aggregate(steps ~ interval, data = data, FUN = mean)
fillNA <- numeric()
for (i in 1:nrow(data)) {
  obs <- data[i, ]
  if (is.na(obs$steps)) {
    steps <- subset(StepsAverage, interval == obs$interval)$steps
  } else {
    steps <- obs$steps
  }
  fillNA <- c(fillNA, steps)
}

new_table <- data 
new_table$steps <- fillNA
```
```{r}
StepsTotal2 <- aggregate(steps ~ date, data = new_table, sum, na.rm = TRUE)
```
```{r, echo=TRUE}
hist(StepsTotal2$steps, main = "Total steps by day", xlab = "day", col = "purple")
```
```{r, echo=TRUE}
mean(StepsTotal2$steps)
median(StepsTotal2$steps)
```
#Are there differences in activity patterns between weekdays and weekends?
```{r}
day <- weekdays(data$date)
daylevel <- vector()
for (i in 1:nrow(data)) {
  if (day[i] == "Saturday") {
    daylevel[i] <- "Weekend"
  } else if (day[i] == "Sunday") {
    daylevel[i] <- "Weekend"
  } else {
    daylevel[i] <- "Weekday"
  }
}
data$daylevel <- daylevel
data$daylevel <- factor(activity$daylevel)

stepsByDay <- aggregate(steps ~ interval + daylevel, data = data, mean)
names(stepsByDay) <- c("interval", "daylevel", "steps")
```
```{r, echo=TRUE}
xyplot(steps ~ interval | daylevel, stepsByDay, type = "l", layout = c(1, 2), 
       xlab = "Interval", ylab = "Number of steps")
```
